version: "2.1"
services:
  web:
    container_name: "dev-activity_web"
    image: wyveo/nginx-php-fpm:php74
    ports:
      - "8080:80"
    volumes:
      - ./docker/php.ini:/etc/php/7.4/fpm/conf.d/30-booster.ini
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./craft:/usr/share/nginx/craft
      - ./config:/usr/share/nginx/config
      - ./modules:/usr/share/nginx/modules
      - ./storage:/usr/share/nginx/storage:delegated
      - ./templates:/usr/share/nginx/templates
      - ./vendor:/usr/share/nginx/vendor:cached
      - ./web:/usr/share/nginx/web
      - ./.env:/usr/share/nginx/.env
      - ./docker/log:/var/log/nginx:delegated
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    container_name: "dev-activity_db"
    ports:
       - "33060:3306"
    volumes:
       - "./docker/db:/var/lib/mysql"
       - ./docker/.my.cnf:/root/.my.cnf
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: "craftcms"
